version: "3.9"
services:
  chatgpt-next-web:
    profiles: [ "no-proxy" ]
    container_name: chatgpt-next-web
    build: .
    image: nextchat-local
    ports:
      - 9091:3000
    environment:
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - SILICONFLOW_URL=${SILICONFLOW_URL}
      - DEFAULT_MODEL=${DEFAULT_MODEL}
      - CUSTOM_MODELS=${CUSTOM_MODELS}
      - CODE=${CODE}
      - HIDE_USER_API_KEY=${HIDE_USER_API_KEY}
      - DISABLE_FAST_LINK=${DISABLE_FAST_LINK}
      - ENABLE_MCP=${ENABLE_MCP}

  chatgpt-next-web-proxy:
    profiles: [ "proxy" ]
    container_name: chatgpt-next-web-proxy
    build: .
    image: nextchat-local
    ports:
      - 3000:3000
    environment:
      - SILICONFLOW_API_KEY=${SILICONFLOW_API_KEY}
      - SILICONFLOW_URL=${SILICONFLOW_URL}
      - DEFAULT_MODEL=${DEFAULT_MODEL}
      - CUSTOM_MODELS=${CUSTOM_MODELS}
      - CODE=${CODE}
      - PROXY_URL=${PROXY_URL}
      - HIDE_USER_API_KEY=${HIDE_USER_API_KEY}
      - DISABLE_FAST_LINK=${DISABLE_FAST_LINK}
      - ENABLE_MCP=${ENABLE_MCP}
